.Dd 2019-12-12
.Dt TPL 1
.Os
.Sh NAME
.Nm tpl
.Nd shell templating utility
.Sh SYNOPSIS
.Nm
.Op Fl v
.Op Fl o Ar open_delim
.Op Fl c Ar close_delim
.Op Fl -
.Op Ar file
.Sh DESCRIPTION
.Nm
is a shell templating utility that looks for
.Ar open_delim
and
.Ar close_delim
in
.Ar file ,
and executes the commands inside it.

The commands are passed as arguments to
.Ql Ev TPL_SHELL -c
if
.Ev TPL_SHELL
is set, else to
.Ql Ev SHELL -c .
If no
.Ar file
is given,
.Nm
reads from stdin.

Text outside the delimiters is written to stdout. Nesting of blocks is not supported.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl v
Print version information to stderr and exit.
.It Fl o Ar open_delim
Define the opening delimiter (default:
.Sq {{ ) .
.It Fl c Ar close_delim
Define the closing delimiter (default:
.Sq }} ) .
.El
.Sh ENVIRONMENT
.Bl -tag -width Ds
.It Ev TPL_SHELL
The pathname of the shell to which commands are passed.
.El
.Sh EXAMPLES
Parse
.Sq options.conf
and redirect stdout to
.Sq ../options.conf
.Bd -filled -offset indent
$
.Nm
options.conf > ../options.conf
.Ed

Parse commands between delimiters
.Sq [[
and
.Sq ]]
in
.Sq options.conf
.Bd -filled -offset indent
$
.Nm
-o [[ -c ]] options.conf
.Ed

Redirect a here-document to
.Nm
.Bd -filled -offset indent
$
.Nm
<< 'EOF'
.Ed
.Sh SEE ALSO
.Xr sh 1
